### ISSUE TITLE
Tracciamento visitatori

### ISSUE THREAD

**Issue by nelsonmau** [ondata/opendatagiustizia-contest#5]
@rossimail palla a te:
- vai sul sito di google analytics https://www.google.com/intl/it_it/analytics/
- registrati (usando il tuo indirizzo mail o l'indirizzo info@opendatagiustizia.it)
- crea nuovo codice di monitoraggio
- poi dacci qui il codice e lo inseriamo sul sito :)

**Comment by nelsonmau** [comment]
(avvisiamo anche la @ariannatoniolo, non si sa mail :)

**Comment by rossimail** [comment]
Ecco il codice 

UA-82383882-1

Da: Andrea Nelson Mauro notifications@github.com
Risposta: ondata/opendatagiustizia-contest reply@reply.github.com
Data: venerdì 12 agosto 2016 17:11
A: ondata/opendatagiustizia-contest opendatagiustizia-contest@noreply.github.com
Cc: Simone Rossi simone.rossi@ltdfr.it, Mention mention@noreply.github.com
Oggetto: [ondata/opendatagiustizia-contest] Tracciamento visitatori (#5)

@rossimail palla a te:
vai sul sito di google analytics https://www.google.com/intl/it_it/analytics/ 
registrati (usando il tuo indirizzo mail o l'indirizzo info@opendatagiustizia.it)
crea nuovo codice di monitoraggio
poi dacci qui il codice e lo inseriamo sul sito :)
You are receiving this because you were mentioned.

**Comment by nelsonmau** [comment]
perfetto, è online :)

mi aggiungi al profilo analytics come user o admin? grazie!

**Comment by rossimail** [comment]
Vedi se funziona e se ho impostato correttamente l'utenza

da SR con  iPhone

Il giorno 13 ago 2016, alle ore 11:38, Andrea Nelson Mauro notifications@github.com ha scritto:

perfetto, è online :)

mi aggiungi al profilo analytics come user o admin? grazie!

**Comment by nelsonmau** [comment]
yes ora funziona, gracias
